spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    jpa:
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://localhost:27017/
      database: usermgt

