#email properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=delighty83@gmail.com
spring.mail.password=iczgmyggqttmxtte
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true