spring:
  profiles:
    active: mongo # mongo | jpa

  application:
      name: auth-service

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  ldap:
    # Embedded Spring LDAP
    #
    # urls: ldap://localhost:12345
    # base: dc=memorynotfound,dc=com
    # username: uid=admin
    # password: secret
    embedded:
      base-dn: dc=memorynotfound,dc=com
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:schema.ldif
      port: 12345
      validation:
        enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com:
      activedge:
        usermgt: DEBUG
#    root: DEBUG
#  file: ${java.io.tmpdir}/${spring.application.name}.log

security:
  jwt:
    secret: ${introspec_sso_jwt_secret:JwtSecretKey123}
    expiration: 8_60_60_000 # 24 hours

server:
  port: ${introspec_sso_port:9100}
  servlet:
    context-path: /${spring.application.name}
